site_name: Learn You A Haskell for Great Good!
site_description: A beginner's guide to Haskell programming language.
site_author: Miran Lipovača
copyright: Creative Commons Attribution-Noncommercial-Share Alike 3.0 Unported License
theme:
  name: material
  features:
    - navigation.indexes
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - 目录: index.md
  - 01. Introduction: ch01/introduction.md
  - 02. Ready Go: ch02/ready-go.md
  - 03. Types and Type Classes: ch03/type-and-typeclass.md
  - 04. Function Syntax: ch04/syntax-in-function.md
  - 05. Recursion: ch05/recursion.md
  - 06. Higher-Order Functions: ch06/high-order-function.md
  - 07. Modules: ch07/module.md
  - 08. Building Our Own Types and Type Classes: ch08/build-our-own-type-and-typeclass.md
  - 09. Input and Output: ch09/input-and-output.md
  - 10. Functionally Solving Problems: ch10/functionally-solving-problems.md
  - 11. Functors, Applicative Functors, and Monoids: ch11/functors-applicative-functors-and-monoids.md
  - 12. A Fistful of Monad: ch12/a-fistful-of-monads.md
  - 13. For a Few Monad More: ch13/for-a-few-monads-more.md
  - 14. Zippers: ch14/zippers.md
  - FAQ: faq/faq.md
  - Resource: resource/resource.md
  - About: about.md
